POST http://localhost:3000/api/auth/register
Content-Type: application/json

{

    "username": "Lala",
    "mail": "lala@gmail.com",
    "password": "simplon12"

}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{

    "mail": "lala@gmail.com",
    "password": "simplon12"

}

###

GET http://localhost:3000/api/user/1

###

POST http://localhost:3000/api/citation/1
Content-Type: application/json

{

    "content": "Les choux sont verts."

}